import type { CategoryDefinition } from '../../../types/muhurtha.types';

export const SCORE_THRESHOLDS = {
  FIVE_STAR: 88,
  FOUR_STAR: 72,
  THREE_STAR: 52,
  TWO_STAR: 32,
} as const;

export const STAR_DISPLAY = {
  5: '★★★★★',
  4: '★★★★☆',
  3: '★★★☆☆',
  2: '★★☆☆☆',
  1: '★☆☆☆☆',
} as const;

export const TITHIS = [
  { number: 1,  name: 'Pratipada',    nameTa: 'பிரதிபதை',    paksha: 'shukla', quality: 'neutral'     },
  { number: 2,  name: 'Dvitiya',      nameTa: 'துவிதியை',     paksha: 'shukla', quality: 'auspicious'  },
  { number: 3,  name: 'Tritiya',      nameTa: 'திருதியை',     paksha: 'shukla', quality: 'auspicious'  },
  { number: 4,  name: 'Chaturthi',    nameTa: 'சதுர்த்தி',   paksha: 'shukla', quality: 'inauspicious' },
  { number: 5,  name: 'Panchami',     nameTa: 'பஞ்சமி',       paksha: 'shukla', quality: 'auspicious'  },
  { number: 6,  name: 'Shashthi',     nameTa: 'சஷ்டி',        paksha: 'shukla', quality: 'inauspicious' },
  { number: 7,  name: 'Saptami',      nameTa: 'சப்தமி',       paksha: 'shukla', quality: 'auspicious'  },
  { number: 8,  name: 'Ashtami',      nameTa: 'அஷ்டமி',       paksha: 'shukla', quality: 'inauspicious' },
  { number: 9,  name: 'Navami',       nameTa: 'நவமி',          paksha: 'shukla', quality: 'inauspicious' },
  { number: 10, name: 'Dashami',      nameTa: 'தசமி',          paksha: 'shukla', quality: 'auspicious'  },
  { number: 11, name: 'Ekadashi',     nameTa: 'ஏகாதசி',       paksha: 'shukla', quality: 'auspicious'  },
  { number: 12, name: 'Dvadashi',     nameTa: 'துவாதசி',      paksha: 'shukla', quality: 'auspicious'  },
  { number: 13, name: 'Trayodashi',   nameTa: 'திரயோதசி',    paksha: 'shukla', quality: 'auspicious'  },
  { number: 14, name: 'Chaturdashi',  nameTa: 'சதுர்தசி',    paksha: 'shukla', quality: 'inauspicious' },
  { number: 15, name: 'Purnima',      nameTa: 'பௌர்ணமி',      paksha: 'shukla', quality: 'neutral'     },
  { number: 16, name: 'Pratipada',    nameTa: 'பிரதிபதை',    paksha: 'krishna', quality: 'neutral'    },
  { number: 17, name: 'Dvitiya',      nameTa: 'துவிதியை',     paksha: 'krishna', quality: 'auspicious' },
  { number: 18, name: 'Tritiya',      nameTa: 'திருதியை',     paksha: 'krishna', quality: 'auspicious' },
  { number: 19, name: 'Chaturthi',    nameTa: 'சதுர்த்தி',   paksha: 'krishna', quality: 'inauspicious'},
  { number: 20, name: 'Panchami',     nameTa: 'பஞ்சமி',       paksha: 'krishna', quality: 'auspicious' },
  { number: 21, name: 'Shashthi',     nameTa: 'சஷ்டி',        paksha: 'krishna', quality: 'neutral'    },
  { number: 22, name: 'Saptami',      nameTa: 'சப்தமி',       paksha: 'krishna', quality: 'auspicious' },
  { number: 23, name: 'Ashtami',      nameTa: 'அஷ்டமி',       paksha: 'krishna', quality: 'inauspicious'},
  { number: 24, name: 'Navami',       nameTa: 'நவமி',          paksha: 'krishna', quality: 'inauspicious'},
  { number: 25, name: 'Dashami',      nameTa: 'தசமி',          paksha: 'krishna', quality: 'neutral'    },
  { number: 26, name: 'Ekadashi',     nameTa: 'ஏகாதசி',       paksha: 'krishna', quality: 'auspicious' },
  { number: 27, name: 'Dvadashi',     nameTa: 'துவாதசி',      paksha: 'krishna', quality: 'auspicious' },
  { number: 28, name: 'Trayodashi',   nameTa: 'திரயோதசி',    paksha: 'krishna', quality: 'neutral'    },
  { number: 29, name: 'Chaturdashi',  nameTa: 'சதுர்தசி',    paksha: 'krishna', quality: 'inauspicious'},
  { number: 30, name: 'Amavasya',     nameTa: 'அமாவாசை',      paksha: 'krishna', quality: 'inauspicious'},
] as const;

export const NAKSHATRAS = [
  { number: 1,  name: 'Ashwini',           nameTa: 'அஸ்வினி',         type: 'swift',   lord: 'Ketu',    lordTa: 'கேது'   },
  { number: 2,  name: 'Bharani',           nameTa: 'பரணி',             type: 'fierce',  lord: 'Venus',   lordTa: 'சுக்கிரன்'},
  { number: 3,  name: 'Krittika',          nameTa: 'கார்த்திகை',       type: 'mixed',   lord: 'Sun',     lordTa: 'சூரியன்' },
  { number: 4,  name: 'Rohini',            nameTa: 'ரோகிணி',           type: 'fixed',   lord: 'Moon',    lordTa: 'சந்திரன்'},
  { number: 5,  name: 'Mrigashirsha',      nameTa: 'மிருகசீர்ஷம்',    type: 'soft',    lord: 'Mars',    lordTa: 'செவ்வாய்'},
  { number: 6,  name: 'Ardra',             nameTa: 'திருவாதிரை',       type: 'sharp',   lord: 'Rahu',    lordTa: 'ராகு'   },
  { number: 7,  name: 'Punarvasu',         nameTa: 'புனர்பூசம்',       type: 'movable', lord: 'Jupiter', lordTa: 'குரு'   },
  { number: 8,  name: 'Pushya',            nameTa: 'பூசம்',             type: 'swift',   lord: 'Saturn',  lordTa: 'சனி'    },
  { number: 9,  name: 'Ashlesha',          nameTa: 'ஆயில்யம்',         type: 'sharp',   lord: 'Mercury', lordTa: 'புதன்'  },
  { number: 10, name: 'Magha',             nameTa: 'மகம்',              type: 'fierce',  lord: 'Ketu',    lordTa: 'கேது'   },
  { number: 11, name: 'Purva Phalguni',    nameTa: 'பூரம்',             type: 'fierce',  lord: 'Venus',   lordTa: 'சுக்கிரன்'},
  { number: 12, name: 'Uttara Phalguni',   nameTa: 'உத்திரம்',         type: 'fixed',   lord: 'Sun',     lordTa: 'சூரியன்' },
  { number: 13, name: 'Hasta',             nameTa: 'அஸ்தம்',           type: 'swift',   lord: 'Moon',    lordTa: 'சந்திரன்'},
  { number: 14, name: 'Chitra',            nameTa: 'சித்திரை',         type: 'soft',    lord: 'Mars',    lordTa: 'செவ்வாய்'},
  { number: 15, name: 'Swati',             nameTa: 'சுவாதி',           type: 'movable', lord: 'Rahu',    lordTa: 'ராகு'   },
  { number: 16, name: 'Vishakha',          nameTa: 'விசாகம்',           type: 'mixed',   lord: 'Jupiter', lordTa: 'குரு'   },
  { number: 17, name: 'Anuradha',          nameTa: 'அனுஷம்',           type: 'soft',    lord: 'Saturn',  lordTa: 'சனி'    },
  { number: 18, name: 'Jyeshtha',          nameTa: 'கேட்டை',           type: 'sharp',   lord: 'Mercury', lordTa: 'புதன்'  },
  { number: 19, name: 'Mula',              nameTa: 'மூலம்',             type: 'sharp',   lord: 'Ketu',    lordTa: 'கேது'   },
  { number: 20, name: 'Purva Ashadha',     nameTa: 'பூராடம்',           type: 'fierce',  lord: 'Venus',   lordTa: 'சுக்கிரன்'},
  { number: 21, name: 'Uttara Ashadha',    nameTa: 'உத்திராடம்',       type: 'fixed',   lord: 'Sun',     lordTa: 'சூரியன்' },
  { number: 22, name: 'Shravana',          nameTa: 'திருவோணம்',        type: 'movable', lord: 'Moon',    lordTa: 'சந்திரன்'},
  { number: 23, name: 'Dhanishtha',        nameTa: 'அவிட்டம்',         type: 'movable', lord: 'Mars',    lordTa: 'செவ்வாய்'},
  { number: 24, name: 'Shatabhisha',       nameTa: 'சதயம்',             type: 'movable', lord: 'Rahu',    lordTa: 'ராகு'   },
  { number: 25, name: 'Purva Bhadrapada',  nameTa: 'பூரட்டாதி',        type: 'fierce',  lord: 'Jupiter', lordTa: 'குரு'   },
  { number: 26, name: 'Uttara Bhadrapada', nameTa: 'உத்திரட்டாதி',    type: 'fixed',   lord: 'Saturn',  lordTa: 'சனி'    },
  { number: 27, name: 'Revati',            nameTa: 'ரேவதி',             type: 'soft',    lord: 'Mercury', lordTa: 'புதன்'  },
] as const;

export const YOGAS = [
  { number: 1,  name: 'Vishkambha',  nameTa: 'விஷ்கம்பம்',   quality: 'bad'     },
  { number: 2,  name: 'Priti',       nameTa: 'பிரீதி',        quality: 'good'    },
  { number: 3,  name: 'Ayushman',    nameTa: 'ஆயுஷ்மான்',    quality: 'good'    },
  { number: 4,  name: 'Saubhagya',   nameTa: 'சௌபாக்கியம்', quality: 'good'    },
  { number: 5,  name: 'Shobhana',    nameTa: 'சோபனம்',       quality: 'good'    },
  { number: 6,  name: 'Atiganda',    nameTa: 'அதிகண்டம்',    quality: 'bad'     },
  { number: 7,  name: 'Sukarma',     nameTa: 'சுகர்மம்',      quality: 'good'    },
  { number: 8,  name: 'Dhriti',      nameTa: 'திருதி',        quality: 'good'    },
  { number: 9,  name: 'Shula',       nameTa: 'சூலம்',         quality: 'bad'     },
  { number: 10, name: 'Ganda',       nameTa: 'கண்டம்',        quality: 'bad'     },
  { number: 11, name: 'Vriddhi',     nameTa: 'விருத்தி',      quality: 'good'    },
  { number: 12, name: 'Dhruva',      nameTa: 'த்ருவம்',       quality: 'good'    },
  { number: 13, name: 'Vyaghata',    nameTa: 'வ்யாகாதம்',    quality: 'bad'     },
  { number: 14, name: 'Harshana',    nameTa: 'ஹர்ஷணம்',      quality: 'good'    },
  { number: 15, name: 'Vajra',       nameTa: 'வஜ்ரம்',        quality: 'bad'     },
  { number: 16, name: 'Siddhi',      nameTa: 'சித்தி',        quality: 'good'    },
  { number: 17, name: 'Vyatipata',   nameTa: 'வ்யதீபாதம்',   quality: 'bad'     },
  { number: 18, name: 'Variyana',    nameTa: 'வரியான்',       quality: 'good'    },
  { number: 19, name: 'Parigha',     nameTa: 'பரிகம்',        quality: 'bad'     },
  { number: 20, name: 'Shiva',       nameTa: 'சிவம்',         quality: 'good'    },
  { number: 21, name: 'Siddha',      nameTa: 'சித்தம்',       quality: 'good'    },
  { number: 22, name: 'Sadhya',      nameTa: 'சாத்யம்',       quality: 'good'    },
  { number: 23, name: 'Shubha',      nameTa: 'சுபம்',         quality: 'good'    },
  { number: 24, name: 'Shukla',      nameTa: 'சுக்லம்',       quality: 'good'    },
  { number: 25, name: 'Brahma',      nameTa: 'பிரம்மம்',      quality: 'good'    },
  { number: 26, name: 'Aindra',      nameTa: 'இந்திரம்',      quality: 'good'    },
  { number: 27, name: 'Vaidhriti',   nameTa: 'வைத்திருதி',   quality: 'bad'     },
] as const;

export const KARANAS = [
  { number: 1,  name: 'Bava',        nameTa: 'பவம்',          quality: 'good'    },
  { number: 2,  name: 'Balava',      nameTa: 'பாலவம்',        quality: 'good'    },
  { number: 3,  name: 'Kaulava',     nameTa: 'கௌலவம்',       quality: 'good'    },
  { number: 4,  name: 'Taitila',     nameTa: 'தைதிலம்',       quality: 'good'    },
  { number: 5,  name: 'Gara',        nameTa: 'கரஜம்',         quality: 'neutral' },
  { number: 6,  name: 'Vanija',      nameTa: 'வணிஜம்',        quality: 'good'    },
  { number: 7,  name: 'Vishti',      nameTa: 'விஷ்டி (பத்ரா)', quality: 'bad'   },
  { number: 8,  name: 'Shakuni',     nameTa: 'சகுனி',         quality: 'neutral' },
  { number: 9,  name: 'Chatushpada', nameTa: 'சதுஷ்பாத',     quality: 'neutral' },
  { number: 10, name: 'Naga',        nameTa: 'நாகம்',         quality: 'bad'     },
  { number: 11, name: 'Kimstughna',  nameTa: 'கிம்ஸ்துக்ன',  quality: 'bad'     },
] as const;

export const VAARA = [
  { number: 0, name: 'Sunday',    nameTa: 'ஞாயிறு',    lord: 'Sun',     lordTa: 'சூரியன்'  },
  { number: 1, name: 'Monday',    nameTa: 'திங்கள்',    lord: 'Moon',    lordTa: 'சந்திரன்' },
  { number: 2, name: 'Tuesday',   nameTa: 'செவ்வாய்',  lord: 'Mars',    lordTa: 'செவ்வாய்' },
  { number: 3, name: 'Wednesday', nameTa: 'புதன்',      lord: 'Mercury', lordTa: 'புதன்'    },
  { number: 4, name: 'Thursday',  nameTa: 'வியாழன்',   lord: 'Jupiter', lordTa: 'குரு'     },
  { number: 5, name: 'Friday',    nameTa: 'வெள்ளி',    lord: 'Venus',   lordTa: 'சுக்கிரன்'},
  { number: 6, name: 'Saturday',  nameTa: 'சனி',       lord: 'Saturn',  lordTa: 'சனி'      },
] as const;

export const RAHU_KALAM_SLOTS: Record<number, [number, number]> = {
  0: [16.5, 18],
  1: [7.5,  9],
  2: [15,   16.5],
  3: [12,   13.5],
  4: [13.5, 15],
  5: [10.5, 12],
  6: [9,    10.5],
};

export const YAMAGANDAM_SLOTS: Record<number, [number, number]> = {
  0: [12,   13.5],
  1: [10.5, 12],
  2: [9,    10.5],
  3: [7.5,  9],
  4: [6,    7.5],
  5: [15,   16.5],
  6: [13.5, 15],
};

export const KULIGAI_SLOTS: Record<number, [number, number]> = {
  0: [15,   16.5],
  1: [13.5, 15],
  2: [12,   13.5],
  3: [10.5, 12],
  4: [9,    10.5],
  5: [7.5,  9],
  6: [6,    7.5],
};

export const MUHURTHA_CATEGORIES: CategoryDefinition[] = [
  {
    id: 'marriage',
    name: 'Marriage',
    nameTa: 'திருமணம்',
    description: 'Wedding ceremony and related rituals for lifelong union',
    descriptionTa: 'வாழ்நாள் இணைப்புக்கான திருமண விழா மற்றும் சடங்குகள்',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13, 17, 18, 20, 22],
    badTithis: [4, 6, 8, 9, 14, 19, 23, 24, 29, 30],
    goodNakshatras: [4, 7, 8, 12, 13, 14, 17, 22, 25, 27],
    badNakshatras: [6, 9, 18, 19, 2, 10],
    goodDays: [1, 3, 4, 5],
    badDays: [0, 2, 6],
    requiresLagnaCheck: true,
    avoidCombust: true,
    avoidEclipse: true,
  },
  {
    id: 'engagement',
    name: 'Engagement',
    nameTa: 'நிச்சயதார்த்தம்',
    description: 'Engagement and betrothal ceremony',
    descriptionTa: 'நிச்சயதார்த்த விழா மற்றும் ஒப்பந்த சடங்கு',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 7, 8, 12, 13, 14, 17, 22, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: true,
    avoidEclipse: true,
  },
  {
    id: 'house_warming',
    name: 'House Warming',
    nameTa: 'கிரஹப்பிரவேசம்',
    description: 'Griha Pravesh - entering a new home for the first time',
    descriptionTa: 'புதிய வீட்டில் முதல் முறையாக நுழையும் கிரஹப்பிரவேச சடங்கு',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13, 15],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 7, 8, 12, 13, 17, 21, 22, 27],
    badNakshatras: [6, 9, 18, 19, 2],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: true,
    avoidCombust: false,
    avoidEclipse: true,
  },
  {
    id: 'land_purchase',
    name: 'Land Purchase',
    nameTa: 'நில வாங்கல்',
    description: 'Purchase of land or immovable property',
    descriptionTa: 'நிலம் அல்லது அசையா சொத்து வாங்குதல்',
    goodTithis: [2, 3, 5, 7, 10, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 8, 12, 21, 22, 26, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: true,
  },
  {
    id: 'land_registration',
    name: 'Land Registration',
    nameTa: 'நில பதிவு',
    description: 'Registration of land documents at sub-registrar office',
    descriptionTa: 'துணை பதிவாளர் அலுவலகத்தில் நில ஆவண பதிவு',
    goodTithis: [2, 3, 5, 7, 10, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 8, 12, 21, 22, 26, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: true,
  },
  {
    id: 'bhoomi_pooja',
    name: 'Bhoomi Pooja',
    nameTa: 'பூமி பூஜை',
    description: 'Ground breaking ceremony before construction',
    descriptionTa: 'கட்டுமான தொடக்கத்திற்கு முன் நிலத்தை ஆசீர்வதிக்கும் சடங்கு',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 7, 8, 12, 13, 17, 21, 22, 26, 27],
    badNakshatras: [6, 9, 18, 19, 2],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: true,
    avoidCombust: false,
    avoidEclipse: true,
  },
  {
    id: 'foundation',
    name: 'Foundation',
    nameTa: 'அடித்தளம் அமைத்தல்',
    description: 'Laying the foundation stone for new construction',
    descriptionTa: 'புதிய கட்டிடத்திற்கு அடிக்கல் நாட்டுதல்',
    goodTithis: [2, 3, 5, 7, 10, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 8, 12, 17, 21, 22, 26],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: true,
  },
  {
    id: 'roof_installation',
    name: 'Roof Installation',
    nameTa: 'கூரை அமைத்தல்',
    description: 'Thatching or roofing of new building',
    descriptionTa: 'புதிய கட்டிடத்திற்கு கூரை அமைத்தல்',
    goodTithis: [2, 3, 5, 7, 10, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 7, 8, 12, 17, 21, 22, 26],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: false,
  },
  {
    id: 'business_opening',
    name: 'Business Opening',
    nameTa: 'வணிக தொடக்கம்',
    description: 'Grand opening of a new business venture',
    descriptionTa: 'புதிய வணிக நிறுவனத்தின் தொடக்க விழா',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [1, 4, 7, 8, 12, 13, 15, 17, 22, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: true,
    avoidCombust: false,
    avoidEclipse: true,
  },
  {
    id: 'office_opening',
    name: 'Office Opening',
    nameTa: 'அலுவலகம் திறப்பு',
    description: 'Inauguration of a new office premises',
    descriptionTa: 'புதிய அலுவலக வளாகத்தின் திறப்பு விழா',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [1, 4, 7, 8, 12, 13, 17, 22, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: true,
    avoidCombust: false,
    avoidEclipse: true,
  },
  {
    id: 'shop_opening',
    name: 'Shop Opening',
    nameTa: 'கடை திறப்பு',
    description: 'Opening of a new shop or retail store',
    descriptionTa: 'புதிய கடை அல்லது சில்லறை விற்பனை நிலையம் திறப்பு',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [1, 4, 7, 8, 13, 15, 17, 22, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: true,
  },
  {
    id: 'vehicle_purchase',
    name: 'Vehicle Purchase',
    nameTa: 'வாகன வாங்கல்',
    description: 'Purchase of a new vehicle (car, bike, etc.)',
    descriptionTa: 'புதிய வாகனம் (கார், பைக் போன்றவை) வாங்குதல்',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [1, 5, 7, 8, 13, 14, 15, 22, 23, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: false,
  },
  {
    id: 'vehicle_registration',
    name: 'Vehicle Registration',
    nameTa: 'வாகன பதிவு',
    description: 'RTO registration of a new vehicle',
    descriptionTa: 'புதிய வாகனத்தின் RTO பதிவு',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [1, 5, 7, 8, 13, 14, 15, 22, 23, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: false,
  },
  {
    id: 'school_admission',
    name: 'School Admission',
    nameTa: 'பள்ளி சேர்க்கை',
    description: 'First day admission to school',
    descriptionTa: 'பள்ளியில் முதல் நாள் சேர்க்கை',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [1, 3, 7, 8, 9, 13, 15, 17, 22, 27],
    badNakshatras: [6, 18, 19],
    goodDays: [1, 3, 4],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: false,
  },
  {
    id: 'college_admission',
    name: 'College Admission',
    nameTa: 'கல்லூரி சேர்க்கை',
    description: 'College or university enrollment',
    descriptionTa: 'கல்லூரி அல்லது பல்கலைக்கழகத்தில் சேர்க்கை',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [1, 3, 7, 8, 9, 13, 15, 17, 22, 27],
    badNakshatras: [6, 18, 19],
    goodDays: [1, 3, 4],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: false,
  },
  {
    id: 'aksharabhyasam',
    name: 'Aksharabhyasam',
    nameTa: 'அட்சரப்பியாசம்',
    description: 'Ceremony of initiating a child into learning the alphabet',
    descriptionTa: 'குழந்தைக்கு எழுத்து கற்பிக்கும் வித்யாரம்பம் சடங்கு',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [1, 3, 7, 8, 13, 15, 17, 22, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: false,
  },
  {
    id: 'naming_ceremony',
    name: 'Naming Ceremony',
    nameTa: 'நாமகரணம்',
    description: 'Namakarana - formal naming ceremony for newborns',
    descriptionTa: 'புதிதாக பிறந்த குழந்தைக்கு பெயர் சூட்டும் நாமகரண சடங்கு',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [1, 4, 5, 7, 8, 13, 14, 17, 22, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: true,
  },
  {
    id: 'ear_piercing',
    name: 'Ear Piercing',
    nameTa: 'காது குத்துதல்',
    description: 'Karnavedha - ear piercing ceremony for children',
    descriptionTa: 'குழந்தைகளுக்கான கர்ணவேத காது குத்தல் சடங்கு',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [1, 4, 5, 7, 8, 13, 14, 17, 22, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: false,
  },
  {
    id: 'annaprasanam',
    name: 'Annaprasanam',
    nameTa: 'அன்னப்பிராசனம்',
    description: 'First solid food feeding ceremony for infants',
    descriptionTa: 'குழந்தைக்கு முதல் முறையாக திட உணவு ஊட்டும் சடங்கு',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 5, 7, 8, 12, 13, 14, 17, 22, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: false,
  },
  {
    id: 'mottai',
    name: 'Mottai (Tonsure)',
    nameTa: 'முண்டன (மொட்டை)',
    description: 'Chudakarana - first hair shaving ceremony',
    descriptionTa: 'சூடாகரண - குழந்தையின் முதல் முண்டன சடங்கு',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [1, 4, 7, 8, 13, 17, 22, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: false,
  },
  {
    id: 'upanayanam',
    name: 'Upanayanam',
    nameTa: 'உபநயனம்',
    description: 'Sacred thread ceremony - Yagnopaveetham',
    descriptionTa: 'பூணூல் சடங்கு - யஜ்ஞோபவீதம்',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 7, 8, 12, 13, 17, 21, 22, 26, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4],
    badDays: [2, 6],
    requiresLagnaCheck: true,
    avoidCombust: true,
    avoidEclipse: true,
  },
  {
    id: 'medical_treatment',
    name: 'Medical Treatment',
    nameTa: 'மருத்துவ சிகிச்சை',
    description: 'Starting a new medical treatment or therapy',
    descriptionTa: 'புதிய மருத்துவ சிகிச்சை அல்லது தெரபி தொடங்குதல்',
    goodTithis: [1, 2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [1, 3, 7, 8, 13, 15, 17, 22, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: false,
  },
  {
    id: 'surgery',
    name: 'Surgery',
    nameTa: 'அறுவை சிகிச்சை',
    description: 'Elective surgical procedure',
    descriptionTa: 'திட்டமிட்ட அறுவை சிகிச்சை செயல்முறை',
    goodTithis: [1, 2, 3, 5, 7, 10, 11, 12],
    badTithis: [4, 6, 8, 9, 14, 15, 30],
    goodNakshatras: [1, 3, 7, 13, 15, 22, 27],
    badNakshatras: [6, 9, 18, 19, 2, 10],
    goodDays: [1, 3, 4],
    badDays: [2, 5, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: true,
  },
  {
    id: 'ivf',
    name: 'IVF',
    nameTa: 'IVF சிகிச்சை',
    description: 'In-vitro fertilization and fertility treatment',
    descriptionTa: 'கருவில் கருவுறுதல் மற்றும் கருவுறுதல் சிகிச்சை',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 5, 7, 8, 12, 13, 17, 22, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: true,
  },
  {
    id: 'passport',
    name: 'Passport',
    nameTa: 'கடவுச்சீட்டு',
    description: 'Applying for or receiving a passport',
    descriptionTa: 'கடவுச்சீட்டுக்கு விண்ணப்பித்தல் அல்லது பெறுதல்',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [1, 7, 8, 13, 15, 17, 22, 24, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: false,
  },
  {
    id: 'visa',
    name: 'Visa',
    nameTa: 'விசா',
    description: 'Applying for or receiving a visa',
    descriptionTa: 'விசாவிற்கு விண்ணப்பித்தல் அல்லது பெறுதல்',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [1, 7, 8, 13, 15, 17, 22, 24, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: false,
  },
  {
    id: 'foreign_travel',
    name: 'Foreign Travel',
    nameTa: 'வெளிநாட்டு பயணம்',
    description: 'Starting a journey to foreign countries',
    descriptionTa: 'வெளிநாடுகளுக்கு பயணம் மேற்கொள்ளுதல்',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [1, 4, 7, 8, 13, 15, 17, 22, 24, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: true,
  },
  {
    id: 'investment',
    name: 'Investment',
    nameTa: 'முதலீடு',
    description: 'Making financial investments in stocks, mutual funds, etc.',
    descriptionTa: 'பங்குகள், மியூச்சுவல் ஃபண்ட் போன்றவற்றில் நிதி முதலீடு',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 7, 8, 12, 13, 17, 22, 26, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: true,
  },
  {
    id: 'gold_purchase',
    name: 'Gold Purchase',
    nameTa: 'தங்கம் வாங்கல்',
    description: 'Buying gold ornaments or gold as investment',
    descriptionTa: 'தங்க நகைகள் அல்லது முதலீடாக தங்கம் வாங்குதல்',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13, 15],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 5, 7, 8, 12, 13, 14, 17, 22, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: true,
    avoidEclipse: true,
  },
  {
    id: 'silver_purchase',
    name: 'Silver Purchase',
    nameTa: 'வெள்ளி வாங்கல்',
    description: 'Buying silver ornaments or silverware',
    descriptionTa: 'வெள்ளி நகைகள் அல்லது வெள்ளி பாத்திரங்கள் வாங்குதல்',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13, 15],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 5, 7, 8, 13, 14, 17, 22, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: false,
  },
  {
    id: 'temple_kumbabishekam',
    name: 'Temple Kumbabishekam',
    nameTa: 'கோவில் கும்பாபிஷேகம்',
    description: 'Temple consecration and re-consecration ceremony',
    descriptionTa: 'கோவில் பிரதிஷ்டை மற்றும் மறு பிரதிஷ்டை சடங்கு',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13, 15],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 7, 8, 12, 13, 17, 21, 22, 26, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: true,
    avoidCombust: true,
    avoidEclipse: true,
  },
  {
    id: 'homam',
    name: 'Homam',
    nameTa: 'ஹோமம்',
    description: 'Fire ritual and oblation ceremony',
    descriptionTa: 'அக்னி சடங்கு மற்றும் ஆஹுதி விழா',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13, 15],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [1, 4, 7, 8, 12, 13, 17, 21, 22, 26, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [0, 1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: true,
  },
  {
    id: 'yagam',
    name: 'Yagam',
    nameTa: 'யாகம்',
    description: 'Grand Vedic fire sacrifice ceremony',
    descriptionTa: 'பெரிய வேத அக்னி யஜ்ஞம் சடங்கு',
    goodTithis: [5, 10, 11, 12, 13, 15],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 7, 8, 12, 17, 21, 22, 26, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [0, 1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: true,
    avoidCombust: true,
    avoidEclipse: true,
  },
  {
    id: 'deeksha',
    name: 'Deeksha',
    nameTa: 'தீட்சை',
    description: 'Spiritual initiation and sacred vow taking ceremony',
    descriptionTa: 'ஆன்மீக தீட்சை மற்றும் புனித சபதம் எடுக்கும் சடங்கு',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13, 15],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 7, 8, 12, 17, 21, 22, 26, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [0, 1, 3, 4, 5],
    badDays: [2, 6],
    requiresLagnaCheck: false,
    avoidCombust: true,
    avoidEclipse: true,
  },
  {
    id: 'agriculture',
    name: 'Agriculture',
    nameTa: 'விவசாயம்',
    description: 'Sowing seeds, planting crops, starting farm work',
    descriptionTa: 'விதை விதைத்தல், பயிர் நடவு, வேளாண்மை பணி தொடக்கம்',
    goodTithis: [2, 3, 5, 7, 10, 11, 12, 13, 15],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 7, 8, 12, 13, 17, 22, 26, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [0, 2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: false,
  },
  {
    id: 'well_digging',
    name: 'Well Digging',
    nameTa: 'கிணறு தோண்டல்',
    description: 'Digging a water well',
    descriptionTa: 'நீர் கிணறு தோண்டுதல்',
    goodTithis: [2, 3, 5, 7, 10, 12, 13, 15],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 7, 8, 13, 17, 22, 26, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [0, 2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: false,
  },
  {
    id: 'borewell',
    name: 'Borewell',
    nameTa: 'போர்வெல்',
    description: 'Drilling a borewell for groundwater',
    descriptionTa: 'நிலத்தடி நீருக்காக போர்வெல் கொரிக்குதல்',
    goodTithis: [2, 3, 5, 7, 10, 12, 13, 15],
    badTithis: [4, 6, 8, 9, 14, 30],
    goodNakshatras: [4, 7, 8, 13, 17, 22, 26, 27],
    badNakshatras: [6, 9, 18, 19],
    goodDays: [1, 3, 4, 5],
    badDays: [0, 2, 6],
    requiresLagnaCheck: false,
    avoidCombust: false,
    avoidEclipse: false,
  },
];

export const ERROR_MESSAGES = {
  INVALID_DATE: {
    en: 'Invalid date format. Please provide a valid date in YYYY-MM-DD format.',
    ta: 'தவறான தேதி வடிவம். YYYY-MM-DD வடிவத்தில் செல்லுபடியான தேதியை வழங்கவும்.',
  },
  INVALID_TIME: {
    en: 'Invalid time format. Please provide a valid time in HH:MM format.',
    ta: 'தவறான நேர வடிவம். HH:MM வடிவத்தில் செல்லுபடியான நேரத்தை வழங்கவும்.',
  },
  INVALID_LATITUDE: {
    en: 'Invalid latitude. Must be between -90 and 90 degrees.',
    ta: 'தவறான அட்சரேகை. -90 முதல் 90 டிகிரி வரை இருக்க வேண்டும்.',
  },
  INVALID_LONGITUDE: {
    en: 'Invalid longitude. Must be between -180 and 180 degrees.',
    ta: 'தவறான தீர்க்கரேகை. -180 முதல் 180 டிகிரி வரை இருக்க வேண்டும்.',
  },
  INVALID_TIMEZONE: {
    en: 'Invalid timezone. Please provide a valid IANA timezone string.',
    ta: 'தவறான நேர மண்டலம். செல்லுபடியான IANA நேர மண்டல சரத்தை வழங்கவும்.',
  },
  INVALID_CATEGORY: {
    en: 'Invalid muhurtha category. Please select a valid category from the list.',
    ta: 'தவறான முகூர்த்த வகை. பட்டியலிலிருந்து செல்லுபடியான வகையைத் தேர்ந்தெடுக்கவும்.',
  },
  CALCULATION_ERROR: {
    en: 'An error occurred during muhurtha calculation. Please try again.',
    ta: 'முகூர்த்த கணக்கீட்டின் போது பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.',
  },
} as const;

export const ZODIAC_SIGNS = [
  { number: 1,  name: 'Aries',       nameTa: 'மேஷம்',       lord: 'Mars'    },
  { number: 2,  name: 'Taurus',      nameTa: 'ரிஷபம்',      lord: 'Venus'   },
  { number: 3,  name: 'Gemini',      nameTa: 'மிதுனம்',     lord: 'Mercury' },
  { number: 4,  name: 'Cancer',      nameTa: 'கடகம்',        lord: 'Moon'    },
  { number: 5,  name: 'Leo',         nameTa: 'சிம்மம்',     lord: 'Sun'     },
  { number: 6,  name: 'Virgo',       nameTa: 'கன்னி',        lord: 'Mercury' },
  { number: 7,  name: 'Libra',       nameTa: 'துலாம்',       lord: 'Venus'   },
  { number: 8,  name: 'Scorpio',     nameTa: 'விருச்சிகம்', lord: 'Mars'    },
  { number: 9,  name: 'Sagittarius', nameTa: 'தனுசு',        lord: 'Jupiter' },
  { number: 10, name: 'Capricorn',   nameTa: 'மகரம்',        lord: 'Saturn'  },
  { number: 11, name: 'Aquarius',    nameTa: 'கும்பம்',      lord: 'Saturn'  },
  { number: 12, name: 'Pisces',      nameTa: 'மீனம்',        lord: 'Jupiter' },
] as const;

export const BENEFIC_PLANETS = ['Jupiter', 'Venus', 'Mercury', 'Moon'] as const;
export const MALEFIC_PLANETS = ['Saturn', 'Mars', 'Sun', 'Rahu', 'Ketu'] as const;

export const CHALDEAN_ORDER = ['Saturn', 'Jupiter', 'Mars', 'Sun', 'Venus', 'Mercury', 'Moon'] as const;
